spring:
  application:
    name: identity
  
  jpa:
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          batch_size: 25
        order_inserts: true
        order_updates: true
        
  jackson:
    serialization:
      write-dates-as-timestamps: false
    time-zone: Asia/Ho_Chi_Minh
    
  cache:
    type: caffeine
    caffeine:
      spec: maximumSize=1000,expireAfterWrite=5m
      
  task:
    execution:
      pool:
        core-size: 2
        max-size: 10
        queue-capacity: 100
        
server:
  port: ${SERVER_PORT:8080}
  compression:
    enabled: true
  forward-headers-strategy: native
  
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  prometheus:
    metrics:
      export:
        enabled: true

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    
logging:
  level:
    com.quytrg.zoomanagement: ${LOG_LEVEL:DEBUG}
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

api:
  prefix: /api
# cors config
cors:
  allowed-origins: "*"
  api-path: "/api/**"